spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subscriptionmanager
    username: root
    password: root@1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: subscriptionmanager
      value-deserializer: com.subscription.subscriptionserver.kafka.deserializer.KafkaMessageDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: com.subscription.subscriptionserver.kafka.serializer.KafkaMessageSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    mailing:
      topic:
        name: mail
        group-id: mail
grpc:
  port: 7017
  enableReflection: true
server:
  port: 8081
jwt:
  secret: "[B@7344699f"
