// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.subscriptionserver.proto;

public interface CreateSubscriptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.CreateSubscriptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.subscriptionmanager.Subscription subscription = 1;</code>
   * @return Whether the subscription field is set.
   */
  boolean hasSubscription();
  /**
   * <code>.com.subscriptionmanager.Subscription subscription = 1;</code>
   * @return The subscription.
   */
  com.subscriptionserver.proto.Subscription getSubscription();
  /**
   * <code>.com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  com.subscriptionserver.proto.SubscriptionOrBuilder getSubscriptionOrBuilder();
}
