// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscriptionserver.proto;

public interface KafkaMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.KafkaMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *receiver mail
   * </pre>
   *
   * <code>string receiver = 1;</code>
   * @return The receiver.
   */
  java.lang.String getReceiver();
  /**
   * <pre>
   *receiver mail
   * </pre>
   *
   * <code>string receiver = 1;</code>
   * @return The bytes for receiver.
   */
  com.google.protobuf.ByteString
      getReceiverBytes();

  /**
   * <pre>
   *content of mail
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   *content of mail
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
