// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.subscriptionserver.proto;

public interface ListSubscriptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.ListSubscriptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  java.util.List<com.subscriptionserver.proto.Subscription> 
      getSubscriptionList();
  /**
   * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  com.subscriptionserver.proto.Subscription getSubscription(int index);
  /**
   * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  int getSubscriptionCount();
  /**
   * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  java.util.List<? extends com.subscriptionserver.proto.SubscriptionOrBuilder> 
      getSubscriptionOrBuilderList();
  /**
   * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  com.subscriptionserver.proto.SubscriptionOrBuilder getSubscriptionOrBuilder(
      int index);
}
