// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.subscriptionserver.proto;

/**
 * Protobuf type {@code com.subscriptionmanager.ListNewsletterResponse}
 */
public final class ListNewsletterResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.subscriptionmanager.ListNewsletterResponse)
    ListNewsletterResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListNewsletterResponse.newBuilder() to construct.
  private ListNewsletterResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListNewsletterResponse() {
    newsletter_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListNewsletterResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.subscriptionserver.proto.Service.internal_static_com_subscriptionmanager_ListNewsletterResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.subscriptionserver.proto.Service.internal_static_com_subscriptionmanager_ListNewsletterResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.subscriptionserver.proto.ListNewsletterResponse.class, com.subscriptionserver.proto.ListNewsletterResponse.Builder.class);
  }

  public static final int NEWSLETTER_FIELD_NUMBER = 1;
  private java.util.List<com.subscriptionserver.proto.NewsletterDetails> newsletter_;
  /**
   * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.subscriptionserver.proto.NewsletterDetails> getNewsletterList() {
    return newsletter_;
  }
  /**
   * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.subscriptionserver.proto.NewsletterDetailsOrBuilder> 
      getNewsletterOrBuilderList() {
    return newsletter_;
  }
  /**
   * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
   */
  @java.lang.Override
  public int getNewsletterCount() {
    return newsletter_.size();
  }
  /**
   * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
   */
  @java.lang.Override
  public com.subscriptionserver.proto.NewsletterDetails getNewsletter(int index) {
    return newsletter_.get(index);
  }
  /**
   * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
   */
  @java.lang.Override
  public com.subscriptionserver.proto.NewsletterDetailsOrBuilder getNewsletterOrBuilder(
      int index) {
    return newsletter_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < newsletter_.size(); i++) {
      output.writeMessage(1, newsletter_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < newsletter_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, newsletter_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.subscriptionserver.proto.ListNewsletterResponse)) {
      return super.equals(obj);
    }
    com.subscriptionserver.proto.ListNewsletterResponse other = (com.subscriptionserver.proto.ListNewsletterResponse) obj;

    if (!getNewsletterList()
        .equals(other.getNewsletterList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNewsletterCount() > 0) {
      hash = (37 * hash) + NEWSLETTER_FIELD_NUMBER;
      hash = (53 * hash) + getNewsletterList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.subscriptionserver.proto.ListNewsletterResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.subscriptionserver.proto.ListNewsletterResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.subscriptionserver.proto.ListNewsletterResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.subscriptionmanager.ListNewsletterResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.subscriptionmanager.ListNewsletterResponse)
      com.subscriptionserver.proto.ListNewsletterResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subscriptionserver.proto.Service.internal_static_com_subscriptionmanager_ListNewsletterResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subscriptionserver.proto.Service.internal_static_com_subscriptionmanager_ListNewsletterResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subscriptionserver.proto.ListNewsletterResponse.class, com.subscriptionserver.proto.ListNewsletterResponse.Builder.class);
    }

    // Construct using com.subscriptionserver.proto.ListNewsletterResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (newsletterBuilder_ == null) {
        newsletter_ = java.util.Collections.emptyList();
      } else {
        newsletter_ = null;
        newsletterBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.subscriptionserver.proto.Service.internal_static_com_subscriptionmanager_ListNewsletterResponse_descriptor;
    }

    @java.lang.Override
    public com.subscriptionserver.proto.ListNewsletterResponse getDefaultInstanceForType() {
      return com.subscriptionserver.proto.ListNewsletterResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.subscriptionserver.proto.ListNewsletterResponse build() {
      com.subscriptionserver.proto.ListNewsletterResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.subscriptionserver.proto.ListNewsletterResponse buildPartial() {
      com.subscriptionserver.proto.ListNewsletterResponse result = new com.subscriptionserver.proto.ListNewsletterResponse(this);
      int from_bitField0_ = bitField0_;
      if (newsletterBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          newsletter_ = java.util.Collections.unmodifiableList(newsletter_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.newsletter_ = newsletter_;
      } else {
        result.newsletter_ = newsletterBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.subscriptionserver.proto.ListNewsletterResponse) {
        return mergeFrom((com.subscriptionserver.proto.ListNewsletterResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.subscriptionserver.proto.ListNewsletterResponse other) {
      if (other == com.subscriptionserver.proto.ListNewsletterResponse.getDefaultInstance()) return this;
      if (newsletterBuilder_ == null) {
        if (!other.newsletter_.isEmpty()) {
          if (newsletter_.isEmpty()) {
            newsletter_ = other.newsletter_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNewsletterIsMutable();
            newsletter_.addAll(other.newsletter_);
          }
          onChanged();
        }
      } else {
        if (!other.newsletter_.isEmpty()) {
          if (newsletterBuilder_.isEmpty()) {
            newsletterBuilder_.dispose();
            newsletterBuilder_ = null;
            newsletter_ = other.newsletter_;
            bitField0_ = (bitField0_ & ~0x00000001);
            newsletterBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNewsletterFieldBuilder() : null;
          } else {
            newsletterBuilder_.addAllMessages(other.newsletter_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.subscriptionserver.proto.NewsletterDetails m =
                  input.readMessage(
                      com.subscriptionserver.proto.NewsletterDetails.parser(),
                      extensionRegistry);
              if (newsletterBuilder_ == null) {
                ensureNewsletterIsMutable();
                newsletter_.add(m);
              } else {
                newsletterBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.subscriptionserver.proto.NewsletterDetails> newsletter_ =
      java.util.Collections.emptyList();
    private void ensureNewsletterIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        newsletter_ = new java.util.ArrayList<com.subscriptionserver.proto.NewsletterDetails>(newsletter_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.subscriptionserver.proto.NewsletterDetails, com.subscriptionserver.proto.NewsletterDetails.Builder, com.subscriptionserver.proto.NewsletterDetailsOrBuilder> newsletterBuilder_;

    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public java.util.List<com.subscriptionserver.proto.NewsletterDetails> getNewsletterList() {
      if (newsletterBuilder_ == null) {
        return java.util.Collections.unmodifiableList(newsletter_);
      } else {
        return newsletterBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public int getNewsletterCount() {
      if (newsletterBuilder_ == null) {
        return newsletter_.size();
      } else {
        return newsletterBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public com.subscriptionserver.proto.NewsletterDetails getNewsletter(int index) {
      if (newsletterBuilder_ == null) {
        return newsletter_.get(index);
      } else {
        return newsletterBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public Builder setNewsletter(
        int index, com.subscriptionserver.proto.NewsletterDetails value) {
      if (newsletterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsletterIsMutable();
        newsletter_.set(index, value);
        onChanged();
      } else {
        newsletterBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public Builder setNewsletter(
        int index, com.subscriptionserver.proto.NewsletterDetails.Builder builderForValue) {
      if (newsletterBuilder_ == null) {
        ensureNewsletterIsMutable();
        newsletter_.set(index, builderForValue.build());
        onChanged();
      } else {
        newsletterBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public Builder addNewsletter(com.subscriptionserver.proto.NewsletterDetails value) {
      if (newsletterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsletterIsMutable();
        newsletter_.add(value);
        onChanged();
      } else {
        newsletterBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public Builder addNewsletter(
        int index, com.subscriptionserver.proto.NewsletterDetails value) {
      if (newsletterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsletterIsMutable();
        newsletter_.add(index, value);
        onChanged();
      } else {
        newsletterBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public Builder addNewsletter(
        com.subscriptionserver.proto.NewsletterDetails.Builder builderForValue) {
      if (newsletterBuilder_ == null) {
        ensureNewsletterIsMutable();
        newsletter_.add(builderForValue.build());
        onChanged();
      } else {
        newsletterBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public Builder addNewsletter(
        int index, com.subscriptionserver.proto.NewsletterDetails.Builder builderForValue) {
      if (newsletterBuilder_ == null) {
        ensureNewsletterIsMutable();
        newsletter_.add(index, builderForValue.build());
        onChanged();
      } else {
        newsletterBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public Builder addAllNewsletter(
        java.lang.Iterable<? extends com.subscriptionserver.proto.NewsletterDetails> values) {
      if (newsletterBuilder_ == null) {
        ensureNewsletterIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, newsletter_);
        onChanged();
      } else {
        newsletterBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public Builder clearNewsletter() {
      if (newsletterBuilder_ == null) {
        newsletter_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        newsletterBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public Builder removeNewsletter(int index) {
      if (newsletterBuilder_ == null) {
        ensureNewsletterIsMutable();
        newsletter_.remove(index);
        onChanged();
      } else {
        newsletterBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public com.subscriptionserver.proto.NewsletterDetails.Builder getNewsletterBuilder(
        int index) {
      return getNewsletterFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public com.subscriptionserver.proto.NewsletterDetailsOrBuilder getNewsletterOrBuilder(
        int index) {
      if (newsletterBuilder_ == null) {
        return newsletter_.get(index);  } else {
        return newsletterBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public java.util.List<? extends com.subscriptionserver.proto.NewsletterDetailsOrBuilder> 
         getNewsletterOrBuilderList() {
      if (newsletterBuilder_ != null) {
        return newsletterBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(newsletter_);
      }
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public com.subscriptionserver.proto.NewsletterDetails.Builder addNewsletterBuilder() {
      return getNewsletterFieldBuilder().addBuilder(
          com.subscriptionserver.proto.NewsletterDetails.getDefaultInstance());
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public com.subscriptionserver.proto.NewsletterDetails.Builder addNewsletterBuilder(
        int index) {
      return getNewsletterFieldBuilder().addBuilder(
          index, com.subscriptionserver.proto.NewsletterDetails.getDefaultInstance());
    }
    /**
     * <code>repeated .com.subscriptionmanager.NewsletterDetails newsletter = 1;</code>
     */
    public java.util.List<com.subscriptionserver.proto.NewsletterDetails.Builder> 
         getNewsletterBuilderList() {
      return getNewsletterFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.subscriptionserver.proto.NewsletterDetails, com.subscriptionserver.proto.NewsletterDetails.Builder, com.subscriptionserver.proto.NewsletterDetailsOrBuilder> 
        getNewsletterFieldBuilder() {
      if (newsletterBuilder_ == null) {
        newsletterBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.subscriptionserver.proto.NewsletterDetails, com.subscriptionserver.proto.NewsletterDetails.Builder, com.subscriptionserver.proto.NewsletterDetailsOrBuilder>(
                newsletter_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        newsletter_ = null;
      }
      return newsletterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.subscriptionmanager.ListNewsletterResponse)
  }

  // @@protoc_insertion_point(class_scope:com.subscriptionmanager.ListNewsletterResponse)
  private static final com.subscriptionserver.proto.ListNewsletterResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.subscriptionserver.proto.ListNewsletterResponse();
  }

  public static com.subscriptionserver.proto.ListNewsletterResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListNewsletterResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListNewsletterResponse>() {
    @java.lang.Override
    public ListNewsletterResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListNewsletterResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListNewsletterResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.subscriptionserver.proto.ListNewsletterResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

