// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.subscriptionserver.proto;

/**
 * Protobuf type {@code com.subscriptionmanager.ListSubscriptionResponse}
 */
public final class ListSubscriptionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.subscriptionmanager.ListSubscriptionResponse)
    ListSubscriptionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListSubscriptionResponse.newBuilder() to construct.
  private ListSubscriptionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListSubscriptionResponse() {
    subscription_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListSubscriptionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.subscriptionserver.proto.Service.internal_static_com_subscriptionmanager_ListSubscriptionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.subscriptionserver.proto.Service.internal_static_com_subscriptionmanager_ListSubscriptionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.subscriptionserver.proto.ListSubscriptionResponse.class, com.subscriptionserver.proto.ListSubscriptionResponse.Builder.class);
  }

  public static final int SUBSCRIPTION_FIELD_NUMBER = 1;
  private java.util.List<com.subscriptionserver.proto.Subscription> subscription_;
  /**
   * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.subscriptionserver.proto.Subscription> getSubscriptionList() {
    return subscription_;
  }
  /**
   * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.subscriptionserver.proto.SubscriptionOrBuilder> 
      getSubscriptionOrBuilderList() {
    return subscription_;
  }
  /**
   * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  @java.lang.Override
  public int getSubscriptionCount() {
    return subscription_.size();
  }
  /**
   * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  @java.lang.Override
  public com.subscriptionserver.proto.Subscription getSubscription(int index) {
    return subscription_.get(index);
  }
  /**
   * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
   */
  @java.lang.Override
  public com.subscriptionserver.proto.SubscriptionOrBuilder getSubscriptionOrBuilder(
      int index) {
    return subscription_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < subscription_.size(); i++) {
      output.writeMessage(1, subscription_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < subscription_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, subscription_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.subscriptionserver.proto.ListSubscriptionResponse)) {
      return super.equals(obj);
    }
    com.subscriptionserver.proto.ListSubscriptionResponse other = (com.subscriptionserver.proto.ListSubscriptionResponse) obj;

    if (!getSubscriptionList()
        .equals(other.getSubscriptionList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSubscriptionCount() > 0) {
      hash = (37 * hash) + SUBSCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriptionList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.subscriptionserver.proto.ListSubscriptionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.subscriptionserver.proto.ListSubscriptionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.subscriptionserver.proto.ListSubscriptionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.subscriptionmanager.ListSubscriptionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.subscriptionmanager.ListSubscriptionResponse)
      com.subscriptionserver.proto.ListSubscriptionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subscriptionserver.proto.Service.internal_static_com_subscriptionmanager_ListSubscriptionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subscriptionserver.proto.Service.internal_static_com_subscriptionmanager_ListSubscriptionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subscriptionserver.proto.ListSubscriptionResponse.class, com.subscriptionserver.proto.ListSubscriptionResponse.Builder.class);
    }

    // Construct using com.subscriptionserver.proto.ListSubscriptionResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (subscriptionBuilder_ == null) {
        subscription_ = java.util.Collections.emptyList();
      } else {
        subscription_ = null;
        subscriptionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.subscriptionserver.proto.Service.internal_static_com_subscriptionmanager_ListSubscriptionResponse_descriptor;
    }

    @java.lang.Override
    public com.subscriptionserver.proto.ListSubscriptionResponse getDefaultInstanceForType() {
      return com.subscriptionserver.proto.ListSubscriptionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.subscriptionserver.proto.ListSubscriptionResponse build() {
      com.subscriptionserver.proto.ListSubscriptionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.subscriptionserver.proto.ListSubscriptionResponse buildPartial() {
      com.subscriptionserver.proto.ListSubscriptionResponse result = new com.subscriptionserver.proto.ListSubscriptionResponse(this);
      int from_bitField0_ = bitField0_;
      if (subscriptionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          subscription_ = java.util.Collections.unmodifiableList(subscription_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.subscription_ = subscription_;
      } else {
        result.subscription_ = subscriptionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.subscriptionserver.proto.ListSubscriptionResponse) {
        return mergeFrom((com.subscriptionserver.proto.ListSubscriptionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.subscriptionserver.proto.ListSubscriptionResponse other) {
      if (other == com.subscriptionserver.proto.ListSubscriptionResponse.getDefaultInstance()) return this;
      if (subscriptionBuilder_ == null) {
        if (!other.subscription_.isEmpty()) {
          if (subscription_.isEmpty()) {
            subscription_ = other.subscription_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSubscriptionIsMutable();
            subscription_.addAll(other.subscription_);
          }
          onChanged();
        }
      } else {
        if (!other.subscription_.isEmpty()) {
          if (subscriptionBuilder_.isEmpty()) {
            subscriptionBuilder_.dispose();
            subscriptionBuilder_ = null;
            subscription_ = other.subscription_;
            bitField0_ = (bitField0_ & ~0x00000001);
            subscriptionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSubscriptionFieldBuilder() : null;
          } else {
            subscriptionBuilder_.addAllMessages(other.subscription_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.subscriptionserver.proto.Subscription m =
                  input.readMessage(
                      com.subscriptionserver.proto.Subscription.parser(),
                      extensionRegistry);
              if (subscriptionBuilder_ == null) {
                ensureSubscriptionIsMutable();
                subscription_.add(m);
              } else {
                subscriptionBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.subscriptionserver.proto.Subscription> subscription_ =
      java.util.Collections.emptyList();
    private void ensureSubscriptionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        subscription_ = new java.util.ArrayList<com.subscriptionserver.proto.Subscription>(subscription_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.subscriptionserver.proto.Subscription, com.subscriptionserver.proto.Subscription.Builder, com.subscriptionserver.proto.SubscriptionOrBuilder> subscriptionBuilder_;

    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public java.util.List<com.subscriptionserver.proto.Subscription> getSubscriptionList() {
      if (subscriptionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subscription_);
      } else {
        return subscriptionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public int getSubscriptionCount() {
      if (subscriptionBuilder_ == null) {
        return subscription_.size();
      } else {
        return subscriptionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public com.subscriptionserver.proto.Subscription getSubscription(int index) {
      if (subscriptionBuilder_ == null) {
        return subscription_.get(index);
      } else {
        return subscriptionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public Builder setSubscription(
        int index, com.subscriptionserver.proto.Subscription value) {
      if (subscriptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionIsMutable();
        subscription_.set(index, value);
        onChanged();
      } else {
        subscriptionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public Builder setSubscription(
        int index, com.subscriptionserver.proto.Subscription.Builder builderForValue) {
      if (subscriptionBuilder_ == null) {
        ensureSubscriptionIsMutable();
        subscription_.set(index, builderForValue.build());
        onChanged();
      } else {
        subscriptionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public Builder addSubscription(com.subscriptionserver.proto.Subscription value) {
      if (subscriptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionIsMutable();
        subscription_.add(value);
        onChanged();
      } else {
        subscriptionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public Builder addSubscription(
        int index, com.subscriptionserver.proto.Subscription value) {
      if (subscriptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionIsMutable();
        subscription_.add(index, value);
        onChanged();
      } else {
        subscriptionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public Builder addSubscription(
        com.subscriptionserver.proto.Subscription.Builder builderForValue) {
      if (subscriptionBuilder_ == null) {
        ensureSubscriptionIsMutable();
        subscription_.add(builderForValue.build());
        onChanged();
      } else {
        subscriptionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public Builder addSubscription(
        int index, com.subscriptionserver.proto.Subscription.Builder builderForValue) {
      if (subscriptionBuilder_ == null) {
        ensureSubscriptionIsMutable();
        subscription_.add(index, builderForValue.build());
        onChanged();
      } else {
        subscriptionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public Builder addAllSubscription(
        java.lang.Iterable<? extends com.subscriptionserver.proto.Subscription> values) {
      if (subscriptionBuilder_ == null) {
        ensureSubscriptionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subscription_);
        onChanged();
      } else {
        subscriptionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public Builder clearSubscription() {
      if (subscriptionBuilder_ == null) {
        subscription_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        subscriptionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public Builder removeSubscription(int index) {
      if (subscriptionBuilder_ == null) {
        ensureSubscriptionIsMutable();
        subscription_.remove(index);
        onChanged();
      } else {
        subscriptionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public com.subscriptionserver.proto.Subscription.Builder getSubscriptionBuilder(
        int index) {
      return getSubscriptionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public com.subscriptionserver.proto.SubscriptionOrBuilder getSubscriptionOrBuilder(
        int index) {
      if (subscriptionBuilder_ == null) {
        return subscription_.get(index);  } else {
        return subscriptionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public java.util.List<? extends com.subscriptionserver.proto.SubscriptionOrBuilder> 
         getSubscriptionOrBuilderList() {
      if (subscriptionBuilder_ != null) {
        return subscriptionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subscription_);
      }
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public com.subscriptionserver.proto.Subscription.Builder addSubscriptionBuilder() {
      return getSubscriptionFieldBuilder().addBuilder(
          com.subscriptionserver.proto.Subscription.getDefaultInstance());
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public com.subscriptionserver.proto.Subscription.Builder addSubscriptionBuilder(
        int index) {
      return getSubscriptionFieldBuilder().addBuilder(
          index, com.subscriptionserver.proto.Subscription.getDefaultInstance());
    }
    /**
     * <code>repeated .com.subscriptionmanager.Subscription subscription = 1;</code>
     */
    public java.util.List<com.subscriptionserver.proto.Subscription.Builder> 
         getSubscriptionBuilderList() {
      return getSubscriptionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.subscriptionserver.proto.Subscription, com.subscriptionserver.proto.Subscription.Builder, com.subscriptionserver.proto.SubscriptionOrBuilder> 
        getSubscriptionFieldBuilder() {
      if (subscriptionBuilder_ == null) {
        subscriptionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.subscriptionserver.proto.Subscription, com.subscriptionserver.proto.Subscription.Builder, com.subscriptionserver.proto.SubscriptionOrBuilder>(
                subscription_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        subscription_ = null;
      }
      return subscriptionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.subscriptionmanager.ListSubscriptionResponse)
  }

  // @@protoc_insertion_point(class_scope:com.subscriptionmanager.ListSubscriptionResponse)
  private static final com.subscriptionserver.proto.ListSubscriptionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.subscriptionserver.proto.ListSubscriptionResponse();
  }

  public static com.subscriptionserver.proto.ListSubscriptionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListSubscriptionResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListSubscriptionResponse>() {
    @java.lang.Override
    public ListSubscriptionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListSubscriptionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListSubscriptionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.subscriptionserver.proto.ListSubscriptionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

