// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.subscriptionserver.proto;

public interface ListNewsletterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.ListNewsletterRequest)
    com.google.protobuf.MessageOrBuilder {
}
