// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.subscriptionserver.proto;

public interface ListSubscriptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.ListSubscriptionRequest)
    com.google.protobuf.MessageOrBuilder {
}
