// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscriptionserver.proto;

public interface NewsletterDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.NewsletterDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>int32 price = 3;</code>
   * @return The price.
   */
  int getPrice();

  /**
   * <code>int32 validity = 4;</code>
   * @return The validity.
   */
  int getValidity();

  /**
   * <code>string genre = 5;</code>
   * @return The genre.
   */
  java.lang.String getGenre();
  /**
   * <code>string genre = 5;</code>
   * @return The bytes for genre.
   */
  com.google.protobuf.ByteString
      getGenreBytes();
}
