// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.subscriptionserver.proto;

public interface RenewSubscriptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.RenewSubscriptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subscription_id = 1;</code>
   * @return The subscriptionId.
   */
  java.lang.String getSubscriptionId();
  /**
   * <code>string subscription_id = 1;</code>
   * @return The bytes for subscriptionId.
   */
  com.google.protobuf.ByteString
      getSubscriptionIdBytes();
}
