// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.subscriptionserver.proto;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_CreateNewsletterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_CreateNewsletterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_ListNewsletterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_ListNewsletterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_ListNewsletterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_ListNewsletterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_CreateSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_CreateSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_ListSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_ListSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_ListSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_ListSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_DeleteSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_DeleteSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_DeleteSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_DeleteSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_RenewSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_RenewSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_RenewSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_RenewSubscriptionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\027com.subscriptionmanager" +
      "\032\rmessage.proto\"Y\n\027CreateNewsletterReque" +
      "st\022>\n\nnewsletter\030\001 \001(\0132*.com.subscriptio" +
      "nmanager.NewsletterDetails\"\027\n\025ListNewsle" +
      "tterRequest\"X\n\026ListNewsletterResponse\022>\n" +
      "\nnewsletter\030\001 \003(\0132*.com.subscriptionmana" +
      "ger.NewsletterDetails\"X\n\031CreateSubscript" +
      "ionRequest\022;\n\014subscription\030\001 \001(\0132%.com.s" +
      "ubscriptionmanager.Subscription\"\031\n\027ListS" +
      "ubscriptionRequest\"W\n\030ListSubscriptionRe" +
      "sponse\022;\n\014subscription\030\001 \003(\0132%.com.subsc" +
      "riptionmanager.Subscription\"4\n\031DeleteSub" +
      "scriptionRequest\022\027\n\017subscription_id\030\001 \001(" +
      "\t\"\034\n\032DeleteSubscriptionResponse\"3\n\030Renew" +
      "SubscriptionRequest\022\027\n\017subscription_id\030\001" +
      " \001(\t\"X\n\031RenewSubscriptionResponse\022;\n\014sub" +
      "scription\030\001 \001(\0132%.com.subscriptionmanage" +
      "r.Subscription2\374\001\n\021NewsletterService\022r\n\020" +
      "createNewsletter\0220.com.subscriptionmanag" +
      "er.CreateNewsletterRequest\032*.com.subscri" +
      "ptionmanager.NewsletterDetails\"\000\022s\n\016List" +
      "Newsletter\022..com.subscriptionmanager.Lis" +
      "tNewsletterRequest\032/.com.subscriptionman" +
      "ager.ListNewsletterResponse\"\0002\202\004\n\023Subscr" +
      "iptionService\022q\n\022createSubscription\0222.co" +
      "m.subscriptionmanager.CreateSubscription" +
      "Request\032%.com.subscriptionmanager.Subscr" +
      "iption\"\000\022y\n\020listSubscription\0220.com.subsc" +
      "riptionmanager.ListSubscriptionRequest\0321" +
      ".com.subscriptionmanager.ListSubscriptio" +
      "nResponse\"\000\022\177\n\022deleteSubscription\0222.com." +
      "subscriptionmanager.DeleteSubscriptionRe" +
      "quest\0323.com.subscriptionmanager.DeleteSu" +
      "bscriptionResponse\"\000\022|\n\021renewSubscriptio" +
      "n\0221.com.subscriptionmanager.RenewSubscri" +
      "ptionRequest\0322.com.subscriptionmanager.R" +
      "enewSubscriptionResponse\"\000B \n\034com.subscr" +
      "iptionserver.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.subscriptionserver.proto.Message.getDescriptor(),
        });
    internal_static_com_subscriptionmanager_CreateNewsletterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_subscriptionmanager_CreateNewsletterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_CreateNewsletterRequest_descriptor,
        new java.lang.String[] { "Newsletter", });
    internal_static_com_subscriptionmanager_ListNewsletterRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_subscriptionmanager_ListNewsletterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_ListNewsletterRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_subscriptionmanager_ListNewsletterResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_subscriptionmanager_ListNewsletterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_ListNewsletterResponse_descriptor,
        new java.lang.String[] { "Newsletter", });
    internal_static_com_subscriptionmanager_CreateSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_subscriptionmanager_CreateSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_CreateSubscriptionRequest_descriptor,
        new java.lang.String[] { "Subscription", });
    internal_static_com_subscriptionmanager_ListSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_subscriptionmanager_ListSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_ListSubscriptionRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_subscriptionmanager_ListSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_subscriptionmanager_ListSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_ListSubscriptionResponse_descriptor,
        new java.lang.String[] { "Subscription", });
    internal_static_com_subscriptionmanager_DeleteSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_subscriptionmanager_DeleteSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_DeleteSubscriptionRequest_descriptor,
        new java.lang.String[] { "SubscriptionId", });
    internal_static_com_subscriptionmanager_DeleteSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_subscriptionmanager_DeleteSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_DeleteSubscriptionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_com_subscriptionmanager_RenewSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_subscriptionmanager_RenewSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_RenewSubscriptionRequest_descriptor,
        new java.lang.String[] { "SubscriptionId", });
    internal_static_com_subscriptionmanager_RenewSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_subscriptionmanager_RenewSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_RenewSubscriptionResponse_descriptor,
        new java.lang.String[] { "Subscription", });
    com.subscriptionserver.proto.Message.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
