// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscriptionserver.proto;

public interface SubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.Subscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string newsletterId = 2;</code>
   * @return The newsletterId.
   */
  java.lang.String getNewsletterId();
  /**
   * <code>string newsletterId = 2;</code>
   * @return The bytes for newsletterId.
   */
  com.google.protobuf.ByteString
      getNewsletterIdBytes();

  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string validityDate = 4;</code>
   * @return The validityDate.
   */
  java.lang.String getValidityDate();
  /**
   * <code>string validityDate = 4;</code>
   * @return The bytes for validityDate.
   */
  com.google.protobuf.ByteString
      getValidityDateBytes();
}
