// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscriptionserver.proto;

public interface SubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.Subscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *id of subscription
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   *id of subscription
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   *newsletter id for which subscription is created
   * </pre>
   *
   * <code>string newsletter_id = 2;</code>
   * @return The newsletterId.
   */
  java.lang.String getNewsletterId();
  /**
   * <pre>
   *newsletter id for which subscription is created
   * </pre>
   *
   * <code>string newsletter_id = 2;</code>
   * @return The bytes for newsletterId.
   */
  com.google.protobuf.ByteString
      getNewsletterIdBytes();

  /**
   * <pre>
   *username of subscriber
   * </pre>
   *
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <pre>
   *username of subscriber
   * </pre>
   *
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   *validity of subscription
   * </pre>
   *
   * <code>string validity_date = 4;</code>
   * @return The validityDate.
   */
  java.lang.String getValidityDate();
  /**
   * <pre>
   *validity of subscription
   * </pre>
   *
   * <code>string validity_date = 4;</code>
   * @return The bytes for validityDate.
   */
  com.google.protobuf.ByteString
      getValidityDateBytes();
}
